### ISSUE TITLE
Alexa groups are not working

### ISSUE THREAD

**Issue by Dielee** [keatontaylor/custom_components#74] opened 2019-02-11 07:37 UTC
When sending an command to a single echo this works,
but sending an command to a alexa group of devices this won't work. 

This problem concerns tunein and spotify. 
Not sure if other services are affected.

Call service code:
```
{
  "entity_id": "media_player.uberall",
  "media_content_id": "Release Radar",
  "media_content_type": "SPOTIFY"
} 
```
```
{
  "entity_id": "media_player.uberall",
  "media_content_id": "eins live",
  "media_content_type": "TUNEIN"
} 

```

**Comment by alandtse** [comment] 2019-02-11 09:02
Can you try this [workaround](https://www.reddit.com/r/amazonecho/comments/8wxk3g/can_you_add_multiroom_music_playback_to_a_routine/) and let me know if that works? In other words, `entity_id` should be changed to a single echo and `media_content_id` should be edited to include the name of your group?

**Comment by Dielee** [comment] 2019-02-11 09:59
Tryed this three versions. All not working for me:

```
{
  "entity_id": "media_player.wohnzimmer",
  "media_content_id": "media_player.uberall.eins live",
  "media_content_type": "TUNEIN"
}
```
```
{
  "entity_id": "media_player.wohnzimmer",
  "media_content_id": "media_player.uberall eins live",
  "media_content_type": "TUNEIN"
}
```
```
{
  "entity_id": "media_player.wohnzimmer",
  "media_content_id": "media_player.uberall",
  "media_content_type": "TUNEIN"
}
```

**Comment by Dielee** [comment] 2019-02-11 10:14
This above works for tunein. 
Unfortunately not working with spotify.

```
{
  "entity_id": "media_player.wohnzimmer",
  "media_content_id": "uberall release radar",
  "media_content_type": "SPOTIFY"
}
```

**Comment by alandtse** [comment] 2019-02-11 10:37
And to verify, if you say "uberall release radar" for Spotify to your Alexa it works, right?

I did see one other post saying you could explicitly mention the group and say `play x in "Everywhere" group`. Does German have a similar use of prepositions and if so, does that help?

Based off the research I did on this, it doesn't look like it's fully supported and it's only reliant on this workaround for now. If so, we may not be able to implement this.

**Comment by alandtse** [comment] 2019-02-11 10:41
Can you also try the equivalent in English? I just realized that we have a hardcoded locale of English in the API for searches which may be confusing it. It may not be the cause since you are able to get German searching to work.

**Comment by alandtse** [comment] 2019-02-12 04:00
Let me see if my English examples explain it. You shouldn't need to say "Play" as it's inherent in the command.

I don't have Spotify so I can't test this, but this is what I think would work based on the links I shared.  If I was to say this in English to my Alexa device, it would be:
"Alexa, play Discover weekly everywhere" 
```json
{
  "entity_id": "media_player.wohnzimmer",
  "media_content_id": "Discover Weekly everywhere",
  "media_content_type": "SPOTIFY"
}
```

or "Alexa, play Discover weekly in the everywhere group"
```json
{
  "entity_id": "media_player.wohnzimmer",
  "media_content_id": "Discover Weekly in the everywhere group",
  "media_content_type": "SPOTIFY"
}
```
Please try both examples in German both speaking and using the service and let me know which combination works and doesn't work.

**Comment by Dielee** [comment] 2019-02-12 09:05
Tested a lot of versions but none works for me...

```

{
  "entity_id": "media_player.wohnzimmer",
  "media_content_id": "Release Radar uberall",
  "media_content_type": "SPOTIFY"
}

{
  "entity_id": "media_player.wohnzimmer",
  "media_content_id": "Discover weekly uberall",
  "media_content_type": "SPOTIFY"
}

{
  "entity_id": "media_player.wohnzimmer",
  "media_content_id": "Discover Weekly everywhere",
  "media_content_type": "SPOTIFY"
}

{
  "entity_id": "media_player.wohnzimmer",
  "media_content_id": "Discover Weekly in the everywhere group",
  "media_content_type": "SPOTIFY"
}

{
  "entity_id": "media_player.wohnzimmer",
  "media_content_id": "Discover Weekly in der uberall gruppe",
  "media_content_type": "SPOTIFY"
}

{
  "entity_id": "media_player.wohnzimmer",
  "media_content_id": "Release Radar in der uberall gruppe",
  "media_content_type": "SPOTIFY"
}
```

**Comment by alandtse** [comment] 2019-02-12 09:20
Ok. You said earlier you can't verbally say the play everywhere to Spotify, right? My googling shows that feature was enabled in Germany last year so I suspect the issues your'e seeing may be linked to the fact the verbal command doesn't work.  I saw one post saying [they had to delete and recreate](https://community.spotify.com/t5/Other-Partners-Web-Player-etc/Amazon-Echo-Multi-room-music/m-p/3973276/highlight/true#M47086) the groups for it to start working.

Can you try that please?

Assuming that doesn't fix it, we may be out of options as normally we can only replicate what the app can do, and I don't see an option in the routines to force it to play everywhere.

**Comment by Dielee** [comment] 2019-02-12 09:37
> You said earlier you can't verbally say the play everywhere to Spotify, right?

Thats wrong. I can verbally say play everywhere and this works every day. 

My echos are only a few months old, so my group is also from late 2018.

**Comment by alandtse** [comment] 2019-02-12 10:42
Sorry, I misunderstood you earlier.  

Hmm. Thanks for your patience and help debugging. If it's misunderstanding the command, I think the last thing we can check is the forced locale issue.  In the Alexa app, can you try creating a routine to play music where the search string is exactly what you have for `media_content_id` in your first two examples?

I will probably fix the component so that it intelligently selects the locale instead of forcing EN-US, but by using the routine builder in the app you'll immediately be able to test this hypothesis as last I checked it sets the correct locale.  As a FYI, this [Wiki page](https://github.com/keatontaylor/custom_components/wiki/Sequence-Discovery) explains how to read the routine builder output.

**Comment by Dielee** [comment] 2019-02-12 11:56
GOT IT WORKING ! 
The test inside off the alexa app was very helpful.

So, sometimes the API uses "u" and sometimes it uses "ü".
In german those are called "Umlaute" (ü,ä,ö) .. shity german.

My group is called "Überall". HA makes "uberall" from "Überall".
I don't now why, but for 1Live ONLY working this:
```
{
  "entity_id": "media_player.wohnzimmer",
  "media_content_id": "uberall eins live",
  "media_content_type": "TUNEIN"
}
```
For BBC1 and Spotify is working ONLY this:
```
{
  "entity_id": "media_player.wohnzimmer",
  "media_content_id": "überall Release Radar",
  "media_content_type": "SPOTIFY"
}
```
If i'm using "ü" for 1Live:
```
{
  "entity_id": "media_player.wohnzimmer",
  "media_content_id": "überall eins live",
  "media_content_type": "TUNEIN"
}
```
it won't work.

**Comment by alandtse** [comment] 2019-02-12 17:25
Glad you got it working. So you're saying in the HA API, you're able to get it to work by switching between a u and umlaut.  

Just to see if I need to fix anything here, did you happen to see if the routines consistently used the right locale setting?  For example, did the locale setting change to DE for SPOTIFY and EN for TUNEIN?

If that didn't happen, I suspect it may be related to how each service processes umlauts.

**Comment by Dielee** [comment] 2019-02-13 12:10
Tested it and the locale setting seems to be de-de all the time. 

![2019-02-13 13_06_48-window](https://user-images.githubusercontent.com/45101649/52710841-aade4400-2f90-11e9-8236-ed43313745eb.png)

![2019-02-13 13_07_44-window](https://user-images.githubusercontent.com/45101649/52710822-9b5efb00-2f90-11e9-9f90-607d24ecfaae.png)

**Comment by alandtse** [comment] 2019-02-13 17:47
Ok, but even with de-DE you're getting the inconsistent umlaut behavior in TUNEIN and SPOTIFY right?

**Comment by Dielee** [comment] 2019-02-14 06:59
Yes, TUNEIN using sometimes 'ü' and sometimes 'u'. Spotify seems to using all the time 'ü'.

**Comment by alandtse** [comment] 2019-02-20 07:54
Closing out as it appears to be an Amazon issue with processing umlauts. Will spawn a new issue to cover the proper locale.

**Closed by alandtse** 2019-02-20 07:54 UTC
